services:
  - type: web
    name: promptly-backend
    env: node
    plan: starter
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CLIENT
        value: sqlite3
      - key: DB_FILENAME
        value: ./database/promptly.db
      - key: ALLOWED_ORIGINS
        value: https://promptly-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

  - type: web
    name: promptly-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://promptly-backend.onrender.com/api/v1
